### ISSUE TITLE
Superpixel dataset

### ISSUE THREAD

**Issue by jamzad** [graphdeeplearning/graphtransformer#6]
Thanks for sharing codes for your interesting paper. I'm interested in applying this method to MNIST superpixel dataset (your benchmarking work) where the task is graph classification, graphs have both node features and edge features, and the number of nodes/edges are different between graphs. What modifications should I made to the current code?

**Comment by vijaydwivedi75** [comment]
Hi @jamzad,

Since this repo is based on the benchmarking gnns code, it should be straightforward.

You can follow the [instructions here](https://github.com/graphdeeplearning/benchmarking-gnns/blob/master/docs/05_add_mpgcn.md) for adding a new model in the benchmark repo, and can easily adapt for the mentioned task by using the graph transformer related files in the benchmark repo. 

Best,
Vijay

**Comment by jamzad** [comment]
Great, thank you @vijaydwivedi75
I was using the previous version where Dataset collate had 3 outputs (with norms). I'll update to new version.
